# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as builder-runner

# Copy requirements first
COPY requirements.txt .

RUN . /cachi2/cachi2.env && \
    ls -l /cachi2/output/deps/pip/ || true && \
    microdnf install -y skopeo jq python3 python3-pip python3-setuptools && \
    mkdir -p /tmp/wheel-src && \
    python3 -m tarfile -e /cachi2/output/deps/pip/wheel-0.42.0.tar.gz /tmp/wheel-src && \
    cd /tmp/wheel-src/wheel-0.42.0 && \
    python3 setup.py install && \
    cd / && rm -rf /tmp/wheel-src && \
    python3 -m pip install --no-index --no-build-isolation --no-deps --find-links=/cachi2/output/deps/pip -r requirements.txt && \
    microdnf clean all

# Use a new stage to enable caching
FROM builder-runner as builder

COPY bundle-hack .
COPY marin3r/bundle/manifests /manifests/
COPY marin3r/bundle/metadata /metadata/

RUN ./update_bundle.sh

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=marin3r-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL com.redhat.component="marin3r-operator-bundle-container" \
      name="3scale-mas/marin3r-operator" \
      version="stable" \
      summary="Lighweight, CRD based Envoy control plane for Kubernetes" \
      description="Lighweight, CRD based Envoy control plane for Kubernetes" \
      distribution-scope="public" \
      io.k8s.description="MARIN3R operator" \
      url="https://github.com/3scale-sre/marin3r" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY marin3r/bundle/tests/scorecard /tests/scorecard/