apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/marin3r-product-build?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: marin3r-operator
    appstudio.openshift.io/component: marin3r-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: marin3r-operator-bundle-on-pull-request
  namespace: api-management-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/api-management-tenant/marin3r-operator-bundle:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.marin3r-operator-bundle
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: 
      - {"type": "rpm", "path": "."}
      - {"type": "pip", "path": "."}
  - name: prefetch-dev-package-managers-enabled
    value: "true"
  - name: build-source-image
    value: "true"
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'