apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
  tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:aac8127bc10c95fae3ca1248c1dd96576315f3313bca90c5c9378dbf37954a08
          - name: kind
            value: task
      params:
        - name: image-url
          value: "$(params.output-image)"
        - name: rebuild
          value: "$(params.rebuild)"
        - name: skip-checks
          value: "$(params.skip-checks)"
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:0761f97595d42c87c076797e0d0f66ff572146cad958106b7f5446b182d03394
          - name: kind
            value: task
      when:
        - input: "$(tasks.init.results.build)"
          operator: in
          values:
            - 'true'
      runAfter:
        - init
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
        - name: ociStorage
          value: "$(params.output-image).git"
        - name: ociArtifactExpiresAfter
          value: "$(params.image-expires-after)"
      workspaces:
        - name: basic-auth
          workspace: git-auth
    - name: prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: prefetch-dependencies-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:153ef0382deef840d155f5146f134f39b480523a7d5c38ba9fea2b58792dd4b5
          - name: kind
            value: task
      params:
        - name: input
          value: "$(params.prefetch-input)"
        - name: hermetic
          value: "$(params.hermetic)"
        - name: dev-package-managers
          value: $(params.prefetch-dev-package-managers-enabled)
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: ociStorage
          value: $(params.output-image).prefetch
        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
    - name: build-container
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: buildah-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.4@sha256:2466d6f8787363825fea838598e91ece2c80e063796613a5c13b28ab690dfbb2
          - name: kind
            value: task
      runAfter:
        - clone-repository
      when:
        - input: "$(tasks.init.results.build)"
          operator: in
          values:
            - 'true'
      params:
        - name: IMAGE
          value: "$(params.output-image)"
        - name: DOCKERFILE
          value: "$(params.dockerfile)"
        - name: CONTEXT
          value: "$(params.path-context)"
        - name: HERMETIC
          value: "$(params.hermetic)"
        - name: PREFETCH_INPUT
          value: "$(params.prefetch-input)"
        - name: IMAGE_EXPIRES_AFTER
          value: "$(params.image-expires-after)"
        - name: COMMIT_SHA
          value: "$(tasks.clone-repository.results.commit)"
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: build-source-image
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: source-build-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.2@sha256:82d5951ad6348064ec33473eeb4d2fe6f7a2d3c8f3125927c04756ba35f251d2
          - name: kind
            value: task
      when:
        - input: "$(tasks.init.results.build)"
          operator: in
          values:
            - 'true'
        - input: "$(params.build-source-image)"
          operator: in
          values:
            - 'true'
      runAfter:
        - build-container
      params:
        - name: BINARY_IMAGE
          value: "$(params.output-image)"
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: deprecated-base-image-check
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: deprecated-image-check
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:eb8136b543147b4a3e88ca3cc661ca6a11e303f35f0db44059f69151beea8496
          - name: kind
            value: task
      when:
        - input: "$(params.skip-checks)"
          operator: in
          values:
            - 'false'
      runAfter:
        - build-container
      params:
        - name: IMAGE_URL
          value: $(tasks.build-container.results.IMAGE_URL)
        - name: IMAGE_DIGEST
          value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: clair-scan
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clair-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:7c73e2beca9b8306387efeaf775831440ec799b05a5f5c008a65bb941a1e91f6
          - name: kind
            value: task
      when:
        - input: "$(params.skip-checks)"
          operator: in
          values:
            - 'false'
      runAfter:
        - build-container
      params:
        - name: image-digest
          value: "$(tasks.build-container.results.IMAGE_DIGEST)"
        - name: image-url
          value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: sast-snyk-check
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-snyk-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:89aead32dc21404e4e0913be9668bdd2eea795db3e4caa762fb619044e479cb8
          - name: kind
            value: task
      when:
        - input: "$(params.skip-checks)"
          operator: in
          values:
            - 'false'
      runAfter:
        - build-container
      params:
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: image-digest
          value: "$(tasks.build-container.results.IMAGE_DIGEST)"
        - name: image-url
          value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: clamav-scan
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clamav-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.2@sha256:11b1684965b64f1fa7c65f90a3524413022246a3863eaba188c84eb4bf0b687a
          - name: kind
            value: task
      when:
        - input: "$(params.skip-checks)"
          operator: in
          values:
            - 'false'
      runAfter:
        - build-container
      params:
        - name: image-digest
          value: "$(tasks.build-container.results.IMAGE_DIGEST)"
        - name: image-url
          value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: rpms-signature-scan
      params:
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: rpms-signature-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:998b5466417c324aea94d3e8b302c558aeb13f746976d89a4ff85f1b84a42c2b
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
  params:
    - name: git-url
      type: string
      description: Source Repository URL
    - name: revision
      type: string
      description: Revision of the Source Repository
      default: ''
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - name: path-context
      type: string
      description: Path to the source code of an application's component from where to
        build image.
      default: "."
    - name: dockerfile
      type: string
      description: Path to the Dockerfile inside the context specified by parameter path-context
      default: Dockerfile
    - name: rebuild
      type: string
      description: Force rebuild image
      default: 'false'
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ''
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "false"
      description: Enable dev-package-managers in prefetch task
      name: prefetch-dev-package-managers-enabled
      type: string
    - name: java
      type: string
      description: Java build
      default: 'false'
    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h,
        2d, 3w for hours, days, and weeks, respectively.
      default: ''
    - name: build-source-image
      type: string
      description: Build a source image.
      default: 'false'
  workspaces:
    - name: git-auth
      optional: true
  results:
    - name: IMAGE_URL
      description: ''
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      description: ''
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: CHAINS-GIT_URL
      description: ''
      value: "$(tasks.clone-repository.results.url)"
    - name: CHAINS-GIT_COMMIT
      description: ''
      value: "$(tasks.clone-repository.results.commit)"
  finally:
    - name: show-sbom
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: show-sbom
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:04f15cbce548e1db7770eee3f155ccb2cc0140a6c371dc67e9a34d83673ea0c0
          - name: kind
            value: task
      params:
        - name: IMAGE_URL
          value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: show-summary
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: summary
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:870d9a04d9784840a90b7bf6817cd0d0c4edfcda04b1ba1868cae625a3c3bfcc
          - name: kind
            value: task
      params:
        - name: pipelinerun-name
          value: "$(context.pipelineRun.name)"
        - name: git-url
          value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
        - name: image-url
          value: "$(params.output-image)"
        - name: build-task-status
          value: "$(tasks.build-container.status)"